Vagrant.configure("2") do | config |
	config.vm.box = "debian/trixie64"
	config.vm.synced_folder "./confs", "/vagrant"

	config.vm.define "simarchaS" do | server |
		server.vm.hostname = "simarchaS"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provider "libvirt" do | vb |
			vb.memory = "2048"
			vb.cpus = 2
		end
		server.vm.provision "shell", path: "scripts/setup_server.sh"
	end
end
