Vagrant.configure("2") do |config|

  # Box Ubuntu récente
  config.vm.box = "bento/debian-13"

  # =========================
  # Serveur S
  # =========================
  config.vm.define "imounjedS" do |server|
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    server.vm.hostname = "imounjedS" #a modifier
    server.vm.network "private_network", ip: "192.168.56.110", primary: true
    # Interface principale = host-only avec IP fixe
    server.vm.network "forwarded_port", guest:6443, host:6443
    server.vm.network "forwarded_port", guest:80, host:80


    # Partage du dossier courant vers /vagrant
    # server.vm.synced_folder "./confs", "/vagrant_common/confs"

    # Exécution du script shell
    # server.vm.provision "shell", path: "./scripts/server.sh", args:["192.168.56.110"]
    server.vm.provision "shell", privileged: true, path: "./scripts/server.sh", args: ["192.168.56.110"]

  end


end

