Vagrant.configure("2") do | config |
  config.vm.box = "debian/bookworm64"

  config.vm.define "simarchaS" do | server |
    server.vm.hostname = "simarchaS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do | vb |
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/setup_server.sh"
  end

  config.vm.define "simarchaSW" do | worker |
    worker.vm.hostname = "simarchaSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtalbox" do | vb |
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/setup_worker.sh"
  end
end
