Vagrant.configure("2") do |config|

  # Box Ubuntu récente
  config.vm.box = "bento/debian-13"

  # =========================
  # Serveur S
  # =========================
  config.vm.define "imounjedS" do |server|
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    server.vm.hostname = "imounjedS" #a modifier
    server.vm.network "private_network", ip: "192.168.56.110"
    # Interface principale = host-only avec IP fixe
    server.vm.network "forwarded_port", guest:6443, host:6443


    # Partage du dossier courant vers /vagrant
    # server.vm.synced_folder "./confs", "/vagrant_common"

    # Exécution du script shell
    # server.vm.provision "shell", path: "./scripts/server.sh", args:["192.168.56.110"]
    server.vm.provision "shell", privileged: true, path: "./scripts/server.sh", args: ["192.168.56.110"]

  end

  # =========================
  # Serveur WS
  # =========================
  config.vm.define "imounjedSW" do |ws|
    ws.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end


    ws.vm.hostname = "imounjedSW" # a modifier

    ws.vm.network "private_network", ip: "192.168.56.111"

    # Partage du dossier courant vers /vagrant
    # ws.vm.synced_folder "./confs", "/vagrant_common"

    # Exécution du script shell
    ws.vm.provision "shell", privileged: true, path: "./scripts/serverWorker.sh", args:["192.168.56.110"]

  end

end

